services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    expose:
      - '27017'
    volumes:
      - mongo-data:/data/db

  bot:
    build:
      context: .
      dockerfile: bot.dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./:/bot

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "9010:9000"
    volumes:
      - ./:/api

volumes:
  mongo-data:
